name: Publish Package

on:
  push:
    tags:
      - 'v*.*.*' # Trigger only on version tags (e.g., v0.0.2)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21' # Specify your preferred Node.js version
          registry-url: 'https://registry.npmjs.org/' # npm registry URL

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test # Run tests to ensure code quality

      - name: Build package
        run: npm run build # Builds your modules and main distribution

      - name: Publish to npm
        run: npm run publish:dist # Publishes the built package from the dist folder
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use npm token from GitHub Secrets
