name: Publish Package

on:
  push:
    tags:
      - "sankey-chart@*" # Trigger for sankeychart tags

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' # Specify your preferred Node.js version
          registry-url: 'https://registry.npmjs.org/' # npm registry URL

      - name: Install dependencies
        run: npm install
        working-directory: ./sankey-chart

      - name: Run Tests
        run: npm test
        working-directory: ./sankey-chart

      - name: Build package
        run: npm run build
        working-directory: ./sankey-chart

      - name: Publish to npm
        run: npm publish --access public
        working-directory: ./sankey-chart
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}